"""Add BiomarkerTracking, TimelineEvent, AIInsight models

Revision ID: 375b0651835f
Revises: 
Create Date: 2026-06-19 03:18:59.717687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '375b0651835f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_reports', sa.Column('document_type', sa.String(length=50), nullable=True))
    op.add_column('medical_reports', sa.Column('structured_data', sa.JSON(), nullable=True))
    op.add_column('medical_reports', sa.Column('health_score', sa.Integer(), nullable=True))
    op.add_column('medical_reports', sa.Column('risk_scores', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_reports', 'risk_scores')
    op.drop_column('medical_reports', 'health_score')
    op.drop_column('medical_reports', 'structured_data')
    op.drop_column('medical_reports', 'document_type')
    # ### end Alembic commands ###
